### ISSUE TITLE
`--crpix-center` sets `CRPIX` to zero instead of center when verifying

### ISSUE THREAD

**Issue by mwcraig** [dstndstn/astrometry.net#174]
When I run astrometry.net (local installation) on an image that already contains a WCS and specify `--crpix-center` on the command line, the resulting WCS actually has `CRPIX` at `[0, 0]`.

I see the same behavior with release 0.72 and when I build from source at commit 59afe904e2c095d0b755648b7df975c274272231.

To reproduce:

1. Grab this fits file (32MB): https://www.dropbox.com/s/6dfct0mvo5o4mtn/TIC_83210867.01-S001-R089-C001-rp.fts?dl=0
2. Run `solve-field` on it; the key option is `--crpix-center`: 
`solve-field --obj 100 --scale-low 0.5 --scale-high 0.6 --scale-units arcsecperpix --no-remove-lines --uniformize 0 --use-sextractor --no-plot --corr none --rdls none --match none --wcs none --crpix-center 
 TIC_83210867.01-S001-R089-C001-rp.fts`
3. The fits file output by `solve-field` has crpix at `[0, 0]`:

```
CRPIX1  =                    0 / X reference pixel
CRPIX2  =                    0 / Y reference pixel
```

The original FITS file had `CRPIX` at the center of the image.

Note: This may be related to #79

**Comment by dstndstn** [comment]
Possibly fixed by c7b776c1d0506e3b78f080ba55ee6931136a3655

**Comment by mwcraig** [comment]
This bug is gone in master but was still present in 0.80 -- thanks for the fix!

**Comment by mwcraig** [comment]
Closing, because this has been fixed in the recent release -- thanks!
